Store events in a Redis stream instead of a list
chaoss/grimoirelab-core pull request #8
Opened 2024-07-11 15:56 UTC by jjmerchante

2025-01-15 12:56 UTC, sduenas requested changes
I wonder if you can reduce the PR just to the scope of writing data to the events stream. I think we can add the tasks that process data later.

2025-01-16 10:41 UTC, jjmerchante commented
I updated the PR to include only the change that inserts data in the stream. I also removed the file grimoirelab-dev that was not being used because the contents were moved to runner/commands/run/

2025-01-17 15:49 UTC, sduenas requested changes
It looks good in general. Check my coments, though.

2025-01-17 15:49 UTC, sduenas commented on src/grimoirelab/core/runner/commands/run.py
> +    from grimoirelab.core.scheduler.scheduler import maintain_tasks
Why did you have to move this statement here?

2025-01-17 15:49 UTC, sduenas commented on src/grimoirelab/core/config/settings.py
> +Q_EVENTIZER_JOBS = os.environ.get('GRIMOIRELAB_Q_EVENTIZER_JOBS', 'default')
I think we can use the prefix `GRIMOIRELAB_` to all these variables that can be configured to make it clear they are part of this app and don't come from other.

2025-01-17 15:49 UTC, sduenas commented on src/grimoirelab/core/config/settings.py
> +EVENTS_STREAM_MAX_LENGTH = int(os.environ.get('GRIMOIRELAB_EVENTS_STREAM_MAX_LENGTH', 2 * 10 ** 6))
This looks like a magic number. What is it and why is that the length?

2025-01-17 16:51 UTC, jjmerchante commented on src/grimoirelab/core/runner/commands/run.py
> +    from grimoirelab.core.scheduler.scheduler import maintain_tasks
Because otherwise, it doesn't work. It has to initialize the Django module first, which is done here: https://github.com/chaoss/grimoirelab-core/blob/main/src/grimoirelab/core/runner/cmd.py#L58

If you try to do the import there you get `django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
`

2025-01-17 16:52 UTC, jjmerchante commented on src/grimoirelab/core/config/settings.py
> +EVENTS_STREAM_MAX_LENGTH = int(os.environ.get('GRIMOIRELAB_EVENTS_STREAM_MAX_LENGTH', 2 * 10 ** 6))
This is the stream's limit. Once the stream reaches this capacity, new items will replace older ones. On average, each Git event consumes approximately 2.6 Kb (calculated using MEMORY USAGE). While this size can be reduced, it is important for consumers to read from the stream before it reaches its limit; otherwise, items will be discarded.

I can lower this number, but it depends on the memory of the Redis server.

2025-01-21 10:10 UTC, merged